### PR TITLE
Fix license authors

### PR DESCRIPTION
**Pull request by DifferentialOrange**
For original work license by @fab13n and @MelomanCool see https://github.com/fab13n/checks/issues/2

### CODE REVIEW

**Review by Totktonada — APPROVED** [review]
I'm ok, but, please, include the information about the original authors agreement into the commit message.

**Comment by DifferentialOrange** [comment]
> I'm ok, but, please, include the information about the original authors agreement into the commit message.

Updated commit message.

**Review by yngvar-antonsson — APPROVED** [review]

**Comment by Totktonada** [comment]
Please, do not merge it. We discussing some details with @fab13n at the moment. I'll return here with more information.

**Comment by DifferentialOrange** [comment]
Updated license considering last https://github.com/fab13n/checks/issues/2 update. Seems like the discussion is resolved

**Comment by Totktonada** [comment]
Nice, thanks!

**Pull request merged**
